name: Docker Image CI

on:
  workflow_dispatch:
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Create build tag
      run: IMAGE_TAG=$(date +%s)
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag "ghcr.io/poertsch/robotframeworkdockerimage:$IMAGE_TAG"
    - name: publish the image
      run: docker push "ghcr.io/poertsch/robotframeworkdockerimage:$IMAGE_TAG"
